[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "visual-odometer"
version = "0.4"
readme = "README.md"
dependencies = [
    "numpy==1.26.4",
    "scipy==1.16.0",
    "pillow==11.2.1"

]

[tool.setuptools.packages.find]
where = ["visual_odometer"]

[project.optional-dependencies]
# For running benchmarks and developing new functionalities:
dev = [
    "pandas",
    "matplotlib",
    "opencv-python"
]

# For running tests:
test = [
    "pytest>=8.0.0",
    "pytest-cov",
    "pytest-timeout",
    "pytest-xdist",
]

# For compiling documentation:
doc = [
    "sphinx>=5.0.0,<8.2.0",
    "sphinxcontrib-bibtex",
    "intersphinx_registry",
    "pydata-sphinx-theme>=0.15.2",
    "sphinx-copybutton",
    "sphinx-design>=0.4.0",
    "matplotlib>=3.5",
    "numpydoc",
    "jupytext",
    "myst-nb>=1.2.0",
    "pooch",
    "jupyterlite-sphinx>=0.19.1",
    "jupyterlite-pyodide-kernel",
    "linkify-it-py",
    "tabulate"
]

[project.urls]
source = "https://github.com/odometriavisual/visual-odometer"
download = "https://github.com/odometriavisual/visual-odometer/releases"